### ISSUE TITLE
Docker image does not persist RDB file in  /data

### ISSUE THREAD

**Issue by jleonelion** [RedisLabsModules/rejson#51]
When I use the docker image redislabs/rejson:latest the data does not persist between restarts of the docker container.  See below docker-compose file.  

Using this docker-compose, Redis launches with the rejson module loaded, but it does not persist the data to disk on container shutdown.

```
version: '3'
services:
  redis:
    container_name: redis
    image: redislabs/rejson:latest
    volumes:
      - ./volumes/redis:/data
    ports:
      - "6379:6379"
```

Everything works fine when I use the "redis" Docker image - I clearly see the message "Saving the final RDB snapshot before exiting" after I issue the "docker stop" command.  The RDB file appears in ./volumes/redis director as I would expect.  

Behavior is as expected when I start/stop the docker image using the following docker-compose file
```
version: '3'
services:
  redis:
    container_name: redis
    image: redis
    volumes:
      - ./volumes/redis:/data
    ports:
      - "6379:6379"

```
Please advise if there is something additional that needs to be done so the rejson docker image persists data on container shutdown.

**Comment by dvirsky** [comment]
You are mapping the data volume but not telling the redis instance that this is where the data resides. See here: https://github.com/RedisLabsModules/RediSearch/issues/241

**Comment by jleonelion** [comment]
That is a good thought, but no luck.

Upon "docker inspect" I see that the standard redis image (which behaves as desired and expected) launches the redis server without any arguments (no --dir or anything).
```
            "Cmd": [
                "redis-server"
            ],
```
The rejson image uses almost the same command, but it also specifies a module to load (which makes sense).
```          
           "Cmd": [
                "redis-server",
                "--loadmodule",
                "/usr/lib/redis/modules/rejson.so"
            ],
```
Even when I modify the launch of rejson so --dir is and additional argument provided to redis-server, data still does not get persisted on container shutdown (as it does with the redis image).

I noticed that the working directory for both of these images is /data (per below) and I can also see that the default Redis server config is setup such that data should be persisted to the working directory (see the redis.conf settings here: https://raw.githubusercontent.com/antirez/redis/4.0/redis.conf) 
```
"WorkingDir": "/data",
```
Just to recap, when shutting down the redis container, I see a message that data is being written to disk.  rejson container does not print this message (so I just have a feeling it is somehow setup such that the default behavior of writing memory to disk on shutdown isn't working).  

PS.  If I run the "SAVE" command via redis-cli, data does persist to the expected location (whether or not I specify --dir on startup).  This is to say, it really seems like something with the way redis-server is setup in the rejson image is such that the default behavior of persisting data on shutdown is disabled.

**Comment by dvirsky** [comment]
with no config file redis is not configured to save anything. If you just mount a redis config file and point redis to it everything works fine.

```sh 
docker run -v `pwd`/data:/data -p 6379:6379 redislabs/rejson:latest /data/redis.conf --loadmodule /usr/lib/redis/modules/rejson.so
```

**Comment by jleonelion** [comment]
I was able to get things squared away. Here is what I did.

1. I downloaded a copy of [redis.conf](https://raw.githubusercontent.com/antirez/redis/4.0/redis.conf) and placed it in `pwd`/data
2. Updated the config so "bind 0.0.0.0" and "dir ./"
3. Updated my docker-compose like the below

```
version: '3'
services:
  redis:
    container_name: redis
    image: redislabs/rejson:latest
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"
    command: redis-server /data/redis.conf --loadmodule /usr/lib/redis/modules/rejson.so
```
